debug: false
log_level: "warn"
http_listen: ":80"
smsc_username: "username"
smsc_password: "password"
smsc_sender: "sender name"
balance_notify:
  500: "url"
  1000: "url"
  3000: "url"
redis:
  url: localhost:6379
  password: psw
  db: 0
